### ISSUE TITLE
Is there a way to be notified if a bad parameter was passed to compile?

### ISSUE THREAD

**Issue by MrDesjardins** [messageformat/messageformat#193]
Is there a way to know if a message was missing a parameter? I notice that undefined is used but I would rather be able to log the wrongly formatted message.

E.g.
``` 
const mf = new MessageFormat("en");
const msg = mf.compile("Name: {b}");
 stringValue = msg({a:"a"});
```
I would like to have a way to know the "b" was missing (optionally know that "a" was provided and not required but that is not my main concern).

**Comment by eemeli** [comment]
At the moment, no; the list of message parameters isn't kept anywhere once the message function is generated. It might however make sense to have separate dev and prod mode runtimes, adding more error reporting to the former and removing from the latter. I'll need to have a think about this.

**Comment by odusseys** [comment]
This would be very appreciated. Right now we are using this to generate email templates, but there is no safe way to check that all required variables were properly passed to the compiled message ; this will occasionally result in `undefined` being present in the evaluated string. Perhaps `compile` could take options as an optional third argument, including a `strict` option, which would check that all templated variables are non-nullish. So something like

`
const mf = new MessageFormat("en");
const msgStrict = mf.compile("hello {name}", "en", { strict: true });
const msgLax = mf.compile("hello", "en");

console.log(msgLax({ name: "world"})) // prints 'hello world'
console.log(msgStrict({ name: "world"})) // throws
`

could also be an (optional) argument of the message instead, so something along the lines of 
`msg(variables, {strict: true})`

**Comment by SlexAxton** [comment]
I actually tend to agree with needing an option for throwing, or a place for throwing on your own.

I can't confirm or deny that I sent out 30k emails on behalf of my employer where every message was "message not found". I would have much preferred them to `throw` and then would have been able to retry them. But since they're emails, they live (hypothetically) forever, broken, in 30k email archive boxes.

I don't think it's the right use-case for *everyone.* But the email use-case really sticks out to me as a time where you need 100% correct output, and don't get a second chance.

We can have a strict mode where we throw, or we can also offer a callback where the user can add their own throw.

```jsx
const mf = new MessageFormat("en");
mf.onMessageNotFound((e) => {
  throw new Error('Hope this breaks the renderer and we can try again.')
});
```

**Comment by eemeli** [comment]
@MrDesjardins @odusseys @SlexAxton Have a look at whether #267 would work for you?
