### ISSUE TITLE
Plural Function not found for locale

### ISSUE THREAD

**Issue by charlie-ablett** [messageformat/messageformat#196]
Hi!

I'm wanting to integrate pluralisation as per angular-translate-interpolation-messageformat and I'm not entirely sure I'm doing this right!

I've got messageformat.js v0.1.7 and angular-translate-interpolation-messageformat.js loaded (I got them from this this plunkr http://plnkr.co/edit/0nJoemE52aBSlB6LvLHV?p=preview) - I can't install from npm or bower, as I need to load the files in directly.

I've got Māori language currently switched on (mi-std) and I'm getting the error `Plural Function not found for locale: mi-std`. I'm aware that `mi-std` isn't the correct locale designation, but there are several dialects to be loaded into the system - this is the first of many.

What's the problem? How do I define a plural function, or do I hook it up somehow?

**Comment by eemeli** [comment]
0.1.7 is a really rather ancient (May 2013) release of messageformat, and it's not really supported anymore. From what I've understood, angular-translate [has updated](/angular-translate/angular-translate/pull/1661) to at least messageformat 1.x, which [includes support](../blob/v1.0.0/test/messageformat.js#L144) for passing in custom pluralisation classifier functions instead of looking up the data from the CLDR:

```js
var mf = new MessageFormat({ fake: function(x, ord) { return ord ? 'few' : 'other'; } });
```

This is relevant to your interests as pluralisation rules for Māori do not appear to be included in any Unicode CLDR version, which is what we currently use as their default source.

If you really are stuck with 0.1.7, IIRC you'll need to add the Māori pluralisation function to the `locale/` directory as `mi.js`, but I'd highly recommend updating to a more recent version of the library.

**Comment by eemeli** [comment]
Closing this as presumably solved?

**Comment by AzamatRasulov** [comment]
@eemeli, hi. Could you please tell me, where I could locate `locale/` directory?

**Comment by eemeli** [comment]
@AzamatRasulov It was in the root of the 0.1 and 0.2 releases of messageformat, but was since dropped.

**Comment by AzamatRasulov** [comment]
> @AzamatRasulov It was in the root of the 0.1 and 0.2 releases of messageformat, but was since dropped.

Ok. How can I add my locale then?

**Comment by eemeli** [comment]
I really need quite a bit more info here. What version of messageformat are you working with, are you using it directly or via some other tools, and what more specifically is the problem you're trying to solve?

**Comment by AzamatRasulov** [comment]
@eemeli ,
messageformat v2.3.0,
using it via `@ngx-translate-messageformat-compiler`.

`@ngx-translate-messageformat-compiler` documentation says I need to pre-import all locales I'll need. So I import `locales: ['ru', 'en', 'tg']` and receive console error `Localisation function not found for locale "tg"`. The closest issue I found is this page, so I think I'm facing the same issue as OP.

**Comment by eemeli** [comment]
See [this comment](#issuecomment-392467037) above for an exact match to what's happening with `tg`, and the potential solution offered there.
