### ISSUE TITLE
Undocumented breaking change : ES6 code

### ISSUE THREAD

**Issue by PhiLhoSoft** [messageformat/messageformat#240]
If I understood correctly, in v. 2.2.0, you rewrote the code in ES6.
But with your Babel settings, the generated JS file is still in ES6, which is a breaking change: our application stops working on IE11, which we have to support (used by many customers). I know, right.
IMO, the best course is to change your settings so that ES5 code is generated.
Otherwise, I suggest you go to v. 3.0 and to indicate clearly the limitations of your choice.

Thanks.

**Comment by eemeli** [comment]
Have you tried using the `messageformat/messageformat.js` endpoint, which is transpiled to IE11-friendly minified ES5? The `"browser"` field in the 2.2.0 package.json was misconfigured, but that was fixed by 2.2.1, and now points to the above-mentioned endpoint.

If you are still experiencing issues with 2.2.1, could you given more details about your build system and configuration?

**Comment by PhiLhoSoft** [comment]
I can confirm that the issue is gone for us with messageformat v. 2.2.1, without compiling issue in our Angular project.
Thanks.
