### ISSUE TITLE
Performant fallback handling using prototype chains

### ISSUE THREAD

**Issue by iamahuman** [messageformat/messageformat#266]
Locale fallback is currently handled by the `Messages` class in `messageformat-runtime`, which wraps the message object emitted by the compiler. If we sacrifice the likely highly rare use case of having multiple `Messages` objects on the same message data, we can use prototype chains for locale fallback handling.

This comes with the additional benefit that the user can simply use the native JavaScript property access syntax for using messages, with fallback being automatically implemented by the JavaScript engine.

The chaining is best done at compile time where the missing keys are known so that the runtime doesn't have to scan the object to selectively merge the overridden (i.e. non-fallback) properties. Setting the prototype as objects are created is the most optimal for JavaScript engines and pre-ES5 support (though might be irrelevant in 2019) becomes easier.

**Comment by eemeli** [comment]
I'm not sure that I'm exactly catching the idea here. It might help if you could draft some of the API changes that this might result in? Also, it's good to note that `messageformat-runtime/messages` is by no means the only tool for accessing compiled messages; for example [react-message-context](https://github.com/eemeli/react-message-context/) will work directly with the compiled message modules.

**Comment by iamahuman** [comment]
@eemeli `messageformat-runtime` was just an example and I didn't take enough time to explore other packages, hence the confusion. My apologies.

No significant API change is expected, though it would be one possible way to implement it. Message lookups are currently handled by searching for the path specified by a given key array for the message object and if not found its fallbacks in order. In a large scale server-side app using messageformat with namespaced messages (e.g. `myapp.account.service.auth.action.signup`) and region-specific specialization using fallbacks (e.g. pt-BR -> pt -> en -> ...) iterating each fallback objects _could_ be a bottleneck. Instead, using JavaScript prototypes the fallback lookups may be omitted since it's handled by the language, and if the user knows that the key exists the runtime helper object could be skipped altogether, taking advantage of any property access optimizations.

**Comment by eemeli** [comment]
After some consideration, I'm going to close this. Using prototypical inheritance is an interesting idea, but it's a bit problematic in practice due to the way that it prevents partial overlays. For instance, consider a case where the messages `foo.bar` and `foo.baz` are defined in a fallback locale, and a more specific locale only defines `foo.baz`. With prototypes, the fallback `foo` is not reachable and resolution for `foo.bar` is either not possible or really complicated.

Also, I suspect that this would be tantamount to optimising the wrong thing.

**Comment by iamahuman** [comment]
@eemeli Thank you for maintaining messageformat and taking time to look into this issue as well. I apologize for not expressing my intent clearly in the first place.

I wrote a proof-of-concept implementation in a gist at https://gist.github.com/iamahuman/cc6b6df505f113785b58b3bdede5eede. Following is its result:

```javascript
en_US
  import $M0 from "messages/en.json"
  var $M1 = $M0.bar
  export default Object.setPrototypeOf({
    foo: function(d) { return "(en_US:[foo])"; },
    bar: Object.setPrototypeOf({
      baz: Object.setPrototypeOf({
        qux: function(d) { return "(en_US:[bar.baz.qux])"; }
      }, $M1.baz),
      quux: {
        corge: function(d) { return "(en_US:[bar.quux.corge])"; }
      }
    }, $M1)
  }, $M0)
  
en
  export default {
    quux: function(d) { return "(en:[quux])"; },
    bar: {
      baz: {
        qux: function(d) { return "(en:[bar.baz.qux]) overriden by en_US"; },
        grault: function(d) { return "(en:[bar.baz.grault])"; }
      },
      garply: {
        waldo: function(d) { return "(en:[bar.garply.waldo])"; }
      }
    }
  }
```

The main idea is to improve performance _specifically_ in the partial overlay case, where the runtime has to bail out for fallback should the traversal cut short in the middle of message lookup. The current algorithm appeared not to be the most efficient particularly for the case when the message nesting is deep and the message lookup has to be done an arbitrary number of times.

**Comment by eemeli** [comment]
Ok, I see what you mean with the deeper setPrototypeOf avoiding the problem I mentioned previously. It does still make it more difficult (but not impossible) to iterate through the messages in an object, but that's admittedly a bit of a rarity.

My second argument about this being a bad optimisation still stands. I left that unexplained previously, for which I apologise. In brief, I'm pretty sure that in real-world cases, the "arbitrary number of times" will practically always be a really low number like two or three at most; something like `fr-CA` → `fr` → `en` is about the longest fallback chain I'd expect to ever actually see. So while the lookup cost for a message could be higher in such a situation, it's not really _that_ much higher, and it'll be executed such a limited number of times compared to other operations that optimising it isn't worth the cost.

And to clarify further, the "cost" here would be in terms of complicating the compiler and its API, as the dependency chain would need to be locked in during the build of the message bundle, rather than being determined by later configuration.

This logic is of course premised on my assumptions about this being a target that doesn't really make sense to optimise; if you have an actual use case where the fallback chain is longer, or can show otherwise that this lookup is impacting the performance of an application, then that would be rather valuable input.

**Comment by iamahuman** [comment]
@eemeli By "arbitrary number of times" I meant messages being nested unto themselves (e.g. `role.page.tab.component.subComponent.itemName.mode.field.confirmTransactionAsk`), rather than a long fallback chain (which is high unlikely). If the messages were shallow (i.e. everything is directly under the main message object) then this feature would be much less useful.

Hierarchically nesting messages allows for keeping translations for each UI component separate, either by writing them in separate modules or marking the hierarchy with indentation. Perhaps I could change my use case so that everything resides under the root path, though.

I agree that this will make the bundling process complicated and less flexible. I suppose we can revisit this issue on another day when some more critical use case shows up. After all, this can readily be implemented externally without much hassle, provided that the user is ready for future breakage.
