### ISSUE TITLE
Jest tests failing on clean clone, French number formatting

### ISSUE THREAD

**Issue by samuelneff** [messageformat/messageformat#285]
I cloned the repo, ran `npm i` and then `npm run test`. There were several test failures, all related to French number formatting.

```
  ● Number patterns › [fr] {value, number, #,##0.###} › value: 1234.567

    expect(received).toMatch(expected)

    Expected pattern: /^1\s234,567$/
    Received string:  "1,234.567"

      162 |               else expect(() => msg(param)).toThrow(res.error);
      163 |             } else if (res instanceof RegExp) {
    > 164 |               expect(msg(param)).toMatch(res);
          |                                  ^
      165 |             } else if (Array.isArray(res)) {
      166 |               expect(msg(param)).toMatchObject(res);
      167 |             } else {

      at Object.<anonymous> (packages/messageformat/src/messageformat.test.ts:164:34)
```

Should I expect the tests to run as is? Is there any other environment setup not mentioned?

MessageFormat cloned today, July 7, 2020, running on master.
Mac OS Cataline 10.15.5
Node v12.17.0
NPM 6.14.4

**Comment by eemeli** [comment]
The documentation on this should definitely be improved. The number-formatting code relies on `Intl.NumberFormat`, which in turn relies on the ICU library. Starting from v13, Node.js comes with the full library by default. Before that, a more limited subset was used. A few of the MessageFormat tests target this capability, because it too needs to be tested.

To add this to your environment, install the [full-icu package](https://www.npmjs.com/package/full-icu) and follow its instructions.

**Comment by samuelneff** [comment]
Thank you
