### ISSUE TITLE
get object from compileModule instead string

### ISSUE THREAD

**Issue by Eutrepe** [messageformat/messageformat#349]
It's possible to get object instead string from "compileModule"? Like in previous version with "compile"

**Comment by eemeli** [comment]
Not directly, no. Using that API you would need to e.g. write the output to disk and then `await import()` it. This is intentional, as module compilation is meant to be used a build/compile action.

If you do want to compile an object of messages during runtime, then you should walk through your object and call `mf.compile()` separately for each message.

**Comment by Eutrepe** [comment]
ok, thanks
